name: rustdesk-simbir
  
jobs:

    runs-on: self-hosted
      uses: ./.github/workflows/flutter-build.yml
      secrets: inherit
      with:
        upload-artifact: true
        upload-tag: "nightly"
